name: Release
on:
  push:
    tags: [v*]
jobs:
  publish_packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.300"
          include-prerelease: true
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Pack
        run: dotnet pack --configuration Release --no-build -o nupkgs
      - name: NuGet Push
        run: Get-Item nupkgs/*.nupkg |% { dotnet nuget push $_ --source ${{ secrets.NUGET_SOURCE }} --api-key ${{ secrets.NUGET_APIKEY }} }
        shell: pwsh
